The Pets Update
LikeMyBread/Saylua pull request #120
Opened 2017-05-10 06:41 UTC by LikeMyBread

This adds a lot of stuff, but mostly it adds pets. It'll require reprovisioning to both update models and add some pets to play with.

2017-05-10 06:48 UTC, NoiSek commented on saylua/modules/pets/badwords.py
> +bad_words = ["arse","ballsack","bastard","beastial","bellend","bestial","biatch","bitch","bloody","blowjob","boiolas","bollock","bollok","boner","boob","booob","boooob","booooob","booooooob","breast"
I can't believe I actually read all of these to see what the addition was.

2017-05-10 06:56 UTC, NoiSek requested changes
Nice work! Functionally this is great stuff to see, made a note on one implementation detail I'm iffy on though.

2017-05-10 06:56 UTC, NoiSek commented on saylua/modules/pets/views.py
>  def pet_profile(name):
There is way too much redundancy here, if you're performing the same action 3+ times why not just construct an output string and add / commit / flash all at once at the end?

I would like to see this at least partially simplified for somebody's sake further down the road

2017-05-10 08:47 UTC, tiffz requested changes
Yay!!!

2017-05-10 08:47 UTC, tiffz commented on saylua/modules/pets/views.py
> +                flash("You can't accompany this companion.")
Psttt. Do flash('message', 'error') to make this case display as an error

2017-05-10 08:47 UTC, tiffz commented on saylua/modules/pets/views.py
> +        companion_id = request.form.get('accompany')
Personally, I feel like putting both abandoning and making pets active here is confusing and overloaded. I'd split these into two separate routes and make both redirect to the profile.

2017-05-11 05:17 UTC, NoiSek approved these changes

2017-05-11 05:18 UTC, NoiSek commented on saylua/modules/pets/views.py
> +                flash(companion.name + " is now accompanying you!")
Use dem dere formatted strings next time, `.format()` is your friend.

2017-05-11 07:00 UTC, merged